### ISSUE TITLE
Some popular countries can not be parsed

### ISSUE THREAD

**Issue by dima4p** [wmoxam/phonie#56]
Hello, Wesley.

The gem becomes useless without popular countries.
The following countries are critical, imho:
Andorra, Monaco, Isle of Man, Kazakhstan, Moldova, Macedonia, Venezuela, Tajikistan, Uzbekistan. 

Do you plan to cover them in some future?

Thank you in advance.

**Comment by dima4p** [comment]
http://www.itu.int/oth/T0202.aspx?lang=en&parent=T0202

**Comment by dramalho** [comment]
My 0.02€ is just go ahead and open a [PR yourself](https://github.com/wmoxam/phonie/pulls?q=is%3Apr+is%3Aclosed+author%3Adramalho) , it's relatively easy and we the people thank you for it :)

**Comment by dima4p** [comment]
Yes, as soon as I get data for any of them.
